import { Sequelize } from 'sequelize'
import { config } from './config'

const sequelize = new Sequelize(config.database, config.dbUser, config.dbPass, {
  host: 'localhost',
  dialect: 'postgres',
  logging: false // SQL generated by sequelize show in the terminal like a console.log
})

export default sequelize
